"""Tests for canonicalize_url and _classify_segment."""

import pytest
from main import canonicalize_url, _classify_segment, SegmentStats
import config


# ---------------------------------------------------------------------------
# _classify_segment (Prong 1 – structural heuristics)
# ---------------------------------------------------------------------------

class TestClassifySegment:
    """Unit tests for the low-level segment classifier."""

    # --- :id ---
    def test_pure_numeric(self):
        assert _classify_segment("12345") == ":id"

    def test_single_digit(self):
        assert _classify_segment("0") == ":id"

    def test_long_hex(self):
        assert _classify_segment("a1b2c3d4e5f6a7b8") == ":id"

    def test_uuid(self):
        assert _classify_segment("550e8400-e29b-41d4-a716-446655440000") == ":id"

    # --- :id-:slug ---
    def test_numeric_prefix_slug(self):
        assert _classify_segment("1386286-epstein-did-not-kill-himself") == ":id-:slug"

    def test_numeric_prefix_underscore(self):
        assert _classify_segment("42_some-article-title") == ":id-:slug"

    # --- :slug (high digit ratio) ---
    def test_high_digit_ratio(self):
        # 4 digits out of 10 chars = 40% > 30%; 'x','y','z' are not hex so Rule 2 doesn't fire
        assert _classify_segment("ab12xyz34g") == ":slug"

    # --- :slug (very long) ---
    def test_very_long_segment(self):
        # 't' is not a hex char so Rule 2 is skipped; length > 40 triggers Rule 5
        seg = "t" * 41
        assert _classify_segment(seg) == ":slug"

    # --- None (ambiguous) ---
    def test_normal_word(self):
        assert _classify_segment("about") is None

    def test_short_word(self):
        assert _classify_segment("jobs") is None

    def test_empty(self):
        assert _classify_segment("") is None

    def test_typical_static_path(self):
        assert _classify_segment("calendar") is None

    def test_short_mixed_no_trigger(self):
        # "v2" is short so digit-ratio rule doesn't apply (len <= 4)
        assert _classify_segment("v2") is None


# ---------------------------------------------------------------------------
# canonicalize_url – Prong 1 only (no observed data)
# ---------------------------------------------------------------------------

class TestCanonicalizeUrlProng1:
    """Tests that exercise structural heuristics with no observed data."""

    def test_strips_query_and_fragment(self):
        url = "https://example.com/page?foo=bar#section"
        assert canonicalize_url(url) == "https://example.com/page"

    def test_strips_trailing_slash(self):
        assert canonicalize_url("https://example.com/about/") == "https://example.com/about"

    def test_root_path_preserved(self):
        assert canonicalize_url("https://example.com/") == "https://example.com/"

    def test_lowercases_netloc(self):
        assert canonicalize_url("https://Example.COM/About") == "https://example.com/About"

    def test_numeric_id_segment(self):
        url = "https://example.com/thread/12345"
        assert canonicalize_url(url) == "https://example.com/thread/:id"

    def test_uuid_segment(self):
        url = "https://example.com/item/550e8400-e29b-41d4-a716-446655440000"
        assert canonicalize_url(url) == "https://example.com/item/:id"

    def test_id_slug_combo(self):
        url = "https://forexfactory.com/thread/1386286-trump-was-once-considered"
        assert canonicalize_url(url) == "https://forexfactory.com/thread/:id-:slug"

    def test_hex_hash_segment(self):
        url = "https://example.com/commit/a1b2c3d4e5f6a7b8"
        assert canonicalize_url(url) == "https://example.com/commit/:id"

    def test_very_long_slug(self):
        slug = "this-is-a-really-long-autogenerated-slug-that-exceeds-forty-characters"
        url = f"https://example.com/blog/{slug}"
        assert canonicalize_url(url) == "https://example.com/blog/:slug"

    def test_no_netloc_passthrough(self):
        assert canonicalize_url("/relative/path") == "/relative/path"

    def test_multiple_dynamic_segments(self):
        url = "https://example.com/user/12345/post/67890"
        assert canonicalize_url(url) == "https://example.com/user/:id/post/:id"


# ---------------------------------------------------------------------------
# canonicalize_url – Prong 2A (cardinality-based slug collapsing)
# ---------------------------------------------------------------------------

class TestCanonicalizeUrlProng2A:
    """Cardinality-based collapsing for the last segment."""

    def _make_observed(self, netloc, parent_tuple, values):
        """Helper: build observed_last_segment_values dict."""
        return {(netloc, parent_tuple): set(values)}

    def _make_static(self, netloc, parent_tuple, values):
        """Helper: build observed_static_segments dict."""
        return {(netloc, parent_tuple): set(values)}

    def test_below_threshold_no_collapse(self):
        """Fewer than SLUG_CARDINALITY_THRESHOLD values → keep literal."""
        obs = self._make_observed("www.forexfactory.com", (), ["bobjones", "janedoe"])
        url = "https://www.forexfactory.com/bobjones"
        result = canonicalize_url(url, observed_last_segment_values=obs)
        assert result == "https://www.forexfactory.com/bobjones"

    def test_at_threshold_collapses_unseen(self):
        """Once cardinality >= threshold, new (unseen-as-static) values collapse."""
        threshold = config.SLUG_CARDINALITY_THRESHOLD
        users = [f"user{i}" for i in range(threshold)]
        obs = self._make_observed("www.forexfactory.com", (), users)
        # Static segments are the ones seen before threshold was hit
        static = self._make_static("www.forexfactory.com", (), users)

        # A brand-new username should collapse
        url = "https://www.forexfactory.com/newuser"
        result = canonicalize_url(url, obs, static)
        assert result == "https://www.forexfactory.com/:slug"

    def test_at_threshold_keeps_static(self):
        """Segments locked-in before threshold are never collapsed."""
        threshold = config.SLUG_CARDINALITY_THRESHOLD
        users = [f"user{i}" for i in range(threshold)]
        obs = self._make_observed("www.forexfactory.com", (), users)
        static = self._make_static("www.forexfactory.com", (), users)

        # "user0" was locked in as static → stays literal
        url = "https://www.forexfactory.com/user0"
        result = canonicalize_url(url, obs, static)
        assert result == "https://www.forexfactory.com/user0"


# ---------------------------------------------------------------------------
# ForexFactory-style dynamic user profiles  (/{username})
# ---------------------------------------------------------------------------

class TestForexFactoryUserProfiles:
    """forexfactory.com/bobjones, forexfactory.com/janedoe, etc.

    These are top-level dynamic segments that look like static routes to a
    naïve parser.  The system must eventually learn to collapse them.
    """

    NETLOC = "www.forexfactory.com"

    def _simulate_many_profiles(self, count):
        """Simulate observing `count` unique usernames at the root level."""
        names = [f"user{i}" for i in range(count)]
        obs = {(self.NETLOC, ()): set(names)}
        # First SLUG_CARDINALITY_THRESHOLD are locked as static
        locked = set(names[: config.SLUG_CARDINALITY_THRESHOLD])
        static = {(self.NETLOC, ()): locked}
        return obs, static

    def test_early_profiles_kept_literal(self):
        """Before enough profiles are seen, usernames stay literal."""
        obs, static = self._simulate_many_profiles(3)
        url = f"https://{self.NETLOC}/user1"
        result = canonicalize_url(url, obs, static)
        assert result == f"https://{self.NETLOC}/user1"

    def test_profiles_collapse_after_threshold(self):
        """After threshold, unseen usernames collapse to :slug."""
        obs, static = self._simulate_many_profiles(config.SLUG_CARDINALITY_THRESHOLD)
        url = f"https://{self.NETLOC}/brandnewuser"
        result = canonicalize_url(url, obs, static)
        assert result == f"https://{self.NETLOC}/:slug"

    def test_known_static_route_not_collapsed(self):
        """Real static routes (calendar, forum) stay even when cardinality is high."""
        obs, static = self._simulate_many_profiles(config.SLUG_CARDINALITY_THRESHOLD)
        # Manually add "calendar" to the static set (as the crawler would)
        static[(self.NETLOC, ())].add("calendar")

        url = f"https://{self.NETLOC}/calendar"
        result = canonicalize_url(url, obs, static)
        assert result == f"https://{self.NETLOC}/calendar"

    def test_nav_link_keeps_segment_static(self):
        """Prong 2B: a segment with nav_link_count >= 2 is immune to collapsing."""
        obs, static = self._simulate_many_profiles(config.SLUG_CARDINALITY_THRESHOLD)
        stats = {
            (self.NETLOC, "/forum"): SegmentStats(nav_link_count=3, in_link_count=10),
        }
        # "forum" not in static set, but nav signals save it
        url = f"https://{self.NETLOC}/forum"
        result = canonicalize_url(url, obs, static, stats)
        assert result == f"https://{self.NETLOC}/forum"


# ---------------------------------------------------------------------------
# ZipRecruiter-style dynamic middle segments  (/{company}/jobs)
# ---------------------------------------------------------------------------

class TestZipRecruiterMiddleSegments:
    """ziprecruiter.com/walmart/jobs, ziprecruiter.com/costco/jobs, etc.

    The dynamic segment is in the middle of the URL, not at the end.
    """

    NETLOC = "www.ziprecruiter.com"

    def _simulate_companies(self, companies):
        """Simulate observing many /company/jobs links."""
        # The company segment sits at position 0, parent = ()
        obs = {(self.NETLOC, ()): set(companies)}
        locked = set(companies[: config.SLUG_CARDINALITY_THRESHOLD])
        static = {(self.NETLOC, ()): locked}
        return obs, static

    def test_early_companies_kept_literal(self):
        obs, static = self._simulate_companies(["walmart", "costco"])
        url = f"https://{self.NETLOC}/walmart/jobs"
        result = canonicalize_url(url, obs, static)
        assert result == f"https://{self.NETLOC}/walmart/jobs"

    def test_companies_collapse_after_threshold(self):
        threshold = config.SLUG_CARDINALITY_THRESHOLD
        companies = [f"company{i}" for i in range(threshold)]
        obs, static = self._simulate_companies(companies)
        url = f"https://{self.NETLOC}/newcompany/jobs"
        result = canonicalize_url(url, obs, static)
        # The middle segment collapses, "jobs" stays
        assert result == f"https://{self.NETLOC}/:slug/jobs"

    def test_static_company_kept_after_threshold(self):
        threshold = config.SLUG_CARDINALITY_THRESHOLD
        companies = [f"company{i}" for i in range(threshold)]
        obs, static = self._simulate_companies(companies)
        # company0 was locked in as static
        url = f"https://{self.NETLOC}/company0/jobs"
        result = canonicalize_url(url, obs, static)
        assert result == f"https://{self.NETLOC}/company0/jobs"

    def test_trailing_segment_stays_literal(self):
        """'jobs' should never collapse since it's the same static value."""
        threshold = config.SLUG_CARDINALITY_THRESHOLD
        companies = [f"company{i}" for i in range(threshold)]
        obs, static = self._simulate_companies(companies)

        # Also register "jobs" as always appearing under each company
        # (Every company page links to /company/jobs, so jobs cardinality = 1)
        for company in companies:
            key = (self.NETLOC, (company,))
            obs[key] = {"jobs"}
            static[key] = {"jobs"}

        url = f"https://{self.NETLOC}/newcompany/jobs"
        result = canonicalize_url(url, obs, static)
        assert "/jobs" in result

    def test_multiple_middle_and_end_dynamic(self):
        """e.g. /company/location/jobs where company and location are dynamic."""
        threshold = config.SLUG_CARDINALITY_THRESHOLD
        companies = [f"company{i}" for i in range(threshold)]
        cities = [f"city{i}" for i in range(threshold)]

        obs = {
            (self.NETLOC, ()): set(companies),
            (self.NETLOC, ("newcompany",)): set(cities),
        }
        static = {
            (self.NETLOC, ()): set(companies[:threshold]),
            (self.NETLOC, ("newcompany",)): set(cities[:threshold]),
        }

        url = f"https://{self.NETLOC}/newcompany/newcity/jobs"
        result = canonicalize_url(url, obs, static)
        assert result == f"https://{self.NETLOC}/:slug/:slug/jobs"


# ---------------------------------------------------------------------------
# Prong 2B – navigation/structural signals
# ---------------------------------------------------------------------------

class TestNavSignals:
    """Segments seen in nav/header/footer should remain static."""

    def test_nav_overrides_cardinality(self):
        netloc = "www.example.com"
        threshold = config.SLUG_CARDINALITY_THRESHOLD
        obs = {(netloc, ()): set(f"seg{i}" for i in range(threshold))}
        static = {(netloc, ()): set()}
        stats = {
            (netloc, "/about"): SegmentStats(nav_link_count=5, in_link_count=20),
        }
        url = "https://www.example.com/about"
        result = canonicalize_url(url, obs, static, stats)
        assert result == "https://www.example.com/about"

    def test_non_nav_still_collapses(self):
        netloc = "www.example.com"
        threshold = config.SLUG_CARDINALITY_THRESHOLD
        obs = {(netloc, ()): set(f"seg{i}" for i in range(threshold))}
        static = {(netloc, ()): set()}
        stats = {
            (netloc, "/about"): SegmentStats(nav_link_count=0, in_link_count=20),
        }
        url = "https://www.example.com/about"
        result = canonicalize_url(url, obs, static, stats)
        assert result == "https://www.example.com/:slug"

    def test_nav_count_exactly_two_is_static(self):
        netloc = "www.example.com"
        threshold = config.SLUG_CARDINALITY_THRESHOLD
        obs = {(netloc, ()): set(f"seg{i}" for i in range(threshold))}
        static = {(netloc, ()): set()}
        stats = {
            (netloc, "/contact"): SegmentStats(nav_link_count=2, in_link_count=5),
        }
        url = "https://www.example.com/contact"
        result = canonicalize_url(url, obs, static, stats)
        assert result == "https://www.example.com/contact"


# ---------------------------------------------------------------------------
# Prong 2C – forced dynamic parents (HTML analysis)
# ---------------------------------------------------------------------------

class TestForcedDynamicParents:
    """Parent paths flagged by HTML analysis force child slug collapsing."""

    def test_forced_parent_collapses_child(self):
        netloc = "www.forexfactory.com"
        forced = {(netloc, ())}
        url = f"https://{netloc}/somerandomuser"
        result = canonicalize_url(url, forced_dynamic_parents=forced)
        assert result == f"https://{netloc}/:slug"

    def test_forced_parent_respects_static(self):
        netloc = "www.forexfactory.com"
        forced = {(netloc, ())}
        static = {(netloc, ()): {"calendar", "forum", "news"}}
        url = f"https://{netloc}/calendar"
        result = canonicalize_url(url, observed_static_segments=static, forced_dynamic_parents=forced)
        assert result == f"https://{netloc}/calendar"

    def test_forced_parent_on_nested_path(self):
        netloc = "www.example.com"
        forced = {(netloc, ("blog",))}
        url = f"https://{netloc}/blog/some-article"
        result = canonicalize_url(url, forced_dynamic_parents=forced)
        assert result == f"https://{netloc}/blog/:slug"

    def test_forced_parent_nav_override(self):
        """Nav signals (Prong 2B) beat forced-dynamic (Prong 2C)."""
        netloc = "www.forexfactory.com"
        forced = {(netloc, ())}
        stats = {
            (netloc, "/calendar"): SegmentStats(nav_link_count=3, in_link_count=10),
        }
        url = f"https://{netloc}/calendar"
        result = canonicalize_url(url, segment_stats=stats, forced_dynamic_parents=forced)
        assert result == f"https://{netloc}/calendar"


# ---------------------------------------------------------------------------
# Combined / integration scenarios
# ---------------------------------------------------------------------------

class TestIntegrationScenarios:
    """End-to-end scenarios mixing multiple prongs."""

    def test_forexfactory_thread_with_id_slug(self):
        """thread/1386286-trump → thread/:id-:slug (Prong 1 alone)."""
        url = "https://www.forexfactory.com/thread/1386286-trump-was-once"
        assert canonicalize_url(url) == "https://www.forexfactory.com/thread/:id-:slug"

    def test_forexfactory_attachment_numeric_id(self):
        url = "https://www.forexfactory.com/attachment/987654"
        assert canonicalize_url(url) == "https://www.forexfactory.com/attachment/:id"

    def test_ziprecruiter_job_posting_with_id(self):
        url = "https://www.ziprecruiter.com/jobs/walmart/12345678"
        assert canonicalize_url(url) == "https://www.ziprecruiter.com/jobs/walmart/:id"

    def test_struct_heuristic_plus_cardinality(self):
        """Numeric ID via Prong 1, username via Prong 2A."""
        netloc = "www.example.com"
        threshold = config.SLUG_CARDINALITY_THRESHOLD
        users = [f"u{i}" for i in range(threshold)]
        obs = {(netloc, ()): set(users)}
        static = {(netloc, ()): set(users)}

        url = f"https://{netloc}/newuser/post/99999"
        result = canonicalize_url(url, obs, static)
        # /newuser collapses (Prong 2A), /post stays, /99999 → :id (Prong 1)
        assert result == f"https://{netloc}/:slug/post/:id"

    def test_all_prongs_together(self):
        """Combine Prong 1, 2A, 2B, and 2C in one URL."""
        netloc = "www.complex.com"
        threshold = config.SLUG_CARDINALITY_THRESHOLD

        # Prong 2A data: position-0 has high cardinality
        obs = {(netloc, ()): set(f"cat{i}" for i in range(threshold))}
        static = {(netloc, ()): set(f"cat{i}" for i in range(threshold))}

        # Prong 2B: /docs has nav links so it's protected
        stats = {
            (netloc, "/docs"): SegmentStats(nav_link_count=4, in_link_count=20),
        }

        url = f"https://{netloc}/docs/12345"
        result = canonicalize_url(url, obs, static, stats)
        # "docs" stays (nav signal), "12345" → :id (Prong 1)
        assert result == f"https://{netloc}/docs/:id"

    def test_scheme_defaults_to_https(self):
        url = "https://example.com/page"
        result = canonicalize_url(url)
        assert result.startswith("https://")

    def test_http_scheme_preserved(self):
        url = "http://example.com/page"
        result = canonicalize_url(url)
        assert result.startswith("http://")
